<?php get_header(); ?>
<?php get_template_part('elements/front-banner'); ?>
<?php get_template_part('elements/section-1'); ?>
<?php get_template_part('elements/section-2'); ?>
<?php get_template_part('elements/portfolio'); ?>
<?php get_template_part('elements/testimonials'); ?>
<?php get_template_part('elements/partners'); ?>
<?php get_template_part('elements/blog-section'); ?>
<?php get_template_part('elements/contact'); ?>
<?php get_footer(); ?>